# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:

name: R-CMD-check.yaml

permissions: read-all

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,  r: 'devel',   http-user-agent: 'release'}
          - {os: ubuntu-latest,  r: 'release'}
          - {os: ubuntu-latest,  r: 'oldrel-1'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      # ----- Dependency installation -----

      # oldrel-1: pin ggplot2 to 3.5.x (compatible with ggtree 3.14.0)
      - name: Install deps (oldrel-1, pin ggplot2 to 3.5.x)
        if: matrix.config.r == 'oldrel-1'
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          needs: check
          extra-packages: |
            any::rcmdcheck
            cran::ggplot2@3.5.2

      # Other R versions: normal installation (will get ggplot2 4.x)
      - name: Install deps (others)
        if: matrix.config.r != 'oldrel-1'
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          needs: check
          extra-packages: any::rcmdcheck

      # ----- End of dependency installation -----

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
